package com.example.network

import com.example.BuildConfig
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Query
import java.util.concurrent.TimeUnit

@JsonClass(generateAdapter = true)
data class GeminiPart(
    @Json(name = "text") val text: String? = null
)

@JsonClass(generateAdapter = true)
data class GeminiContent(
    @Json(name = "parts") val parts: List<GeminiPart>
)

@JsonClass(generateAdapter = true)
data class GeminiRequest(
    @Json(name = "contents") val contents: List<GeminiContent>
)

@JsonClass(generateAdapter = true)
data class GeminiCandidate(
    @Json(name = "content") val content: GeminiContent?
)

@JsonClass(generateAdapter = true)
data class GeminiResponse(
    @Json(name = "candidates") val candidates: List<GeminiCandidate>?
)

interface GeminiApi {
    @POST("v1beta/models/gemini-3.5-flash:generateContent")
    suspend fun generateContent(
        @Query("key") apiKey: String,
        @Body request: GeminiRequest
    ): GeminiResponse
}

object GeminiClient {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/"

    private val moshi = Moshi.Builder()
        .addLast(KotlinJsonAdapterFactory())
        .build()

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .addInterceptor(HttpLoggingInterceptor().apply {
            level = HttpLoggingInterceptor.Level.BODY
        })
        .build()

    val api: GeminiApi by lazy {
        Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .build()
            .create(GeminiApi::class.java)
    }

    suspend fun analyzeProduceQuality(
        batchId: String,
        productName: String,
        variety: String,
        tempMin: Double,
        tempMax: Double,
        maxEthylene: Double,
        readingsSummary: String,
        alertsSummary: String
    ): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext "GEMINI_API_KEY is not configured. Please add your key in the AI Studio Secrets panel or .env file to enable live AI quality analytics."
        }

        val prompt = """
            You are FarmTrace AI, an agricultural cold-chain and supply chain quality analytics engine.
            Analyze the following real IoT sensor history for agricultural produce batch:
            - Batch ID: $batchId
            - Product: $productName ($variety)
            - Required Temp Range: $tempMin°C to $tempMax°C
            - Max Permissible Ethylene: $maxEthylene ppm
            
            Telemetry History Summary:
            $readingsSummary
            
            Active Excursion Alerts:
            $alertsSummary
            
            Provide a structured quality analysis containing:
            1. Quality & Freshness Trend: (e.g. Optimal, Moderate Degradation, Accelerated Ripening, or Severe Spoilage Risk)
            2. Primary Risk Factors: (Analysis of cumulative degree-hours above baseline, ethylene exposure, and relative humidity)
            3. Observed Anomalies: (Specific spikes or dropouts observed in recorded data)
            4. Recommended Action: (Specific inspection guidelines for receiver/warehouse manager)
            
            Note: Explicitly maintain a professional, analytical tone and include the standard food safety advisory notice.
        """.trimIndent()

        val request = GeminiRequest(
            contents = listOf(
                GeminiContent(
                    parts = listOf(GeminiPart(text = prompt))
                )
            )
        )

        try {
            val response = api.generateContent(apiKey, request)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                ?: "No analysis generated by model."
        } catch (e: Exception) {
            "AI Analysis unavailable: ${e.localizedMessage ?: e.message}"
        }
    }
}
